### ISSUE TITLE
backward_markers

### ISSUE THREAD

**Issue by wangjio** [jerenchen/deformxfer#1]
Hi，thanks for your great work.
I cannot find 'backward_markers' in paper. What does this mean？

**Comment by jerenchen** [comment]
Backward markers/landmarks are more specific to the application on face blendshapes transfer of [this project](https://github.com/diegothomas/Avatar-generation-3DRW2019-/blob/master/BlendshapeMaker/lib/BMManager.py) which my C++ implementation based upon.

I believe they are the `positional vertex constraints` described in the paper.

**Comment by wangjio** [comment]
Oh, It's my problem. I followed the older paper by Sumner and Popovic in 2004.

**Comment by jerenchen** [comment]
> I believe they are the positional vertex constraints described in the paper.

I was in fact referring to the original Sumner & Popovic 2004 paper :)
